Imports Raymond.Services

Namespace Generators
    Public Interface IPhraseGenerator
        ''' <summary>
        ''' The weight of this generator. Or, how likely it is to be used.
        ''' </summary>
        ReadOnly Property Chance As Double

        ''' <summary>
        ''' The TTS voice to be used when synthesizing the phrase generated by this generator.
        ''' </summary>
        ReadOnly Property TtsVoice As String
        ' List of voices: https://cloud.google.com/text-to-speech/docs/voices
        ' Only en-US compatible voices should be used; preferably WaveNet. 
        ' Set this to Nothing to use the default voice.

        ''' <summary>
        ''' Returns a randomly chosen phrase or sentence.
        ''' </summary>
        Function GeneratePhrase(numberGenerator As NumberService) As String
    End Interface
End Namespace